### ISSUE TITLE
Cannot be installed if the application was renamed from "\App" namespace!

### ISSUE THREAD

**Issue by gildniy** [sgrover/o2susers#1]
Hello, the package is designed only for applications having as name "App", can you plz consider some people who renamed their applications to something like "Blabla"? Because the vendor try to search something like "App\Http\Controllers\Controller" intead of "Blabla\Http\Controllers\Controller".

Thanks!

**Comment by sgrover** [comment]
Should be resolved to handle non-standard namespaces now.

**Comment by gildniy** [comment]
Thanks for the update. I appreciate your efforts :+1:
